# Load and save

Код считывает файл, обрабатывает его и сохраняет результат в файл.

## 1. read_csv

In [13]:
import pandas as pd


input_file = "../data/feed-views.log"
output_file = "../data/feed-views-semicolon.log"

df = pd.read_csv(
    input_file,
    sep='\t',
    header=None,
    names=["datetime", "user"],
    skiprows=[2, 3],
    skipfooter=2,
    engine="python"
    )

- Вывод head датафрейма

In [14]:
df.head()

                     datetime    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana

- Вывод tail датафрейма

In [15]:
df.tail()

                        datetime       user
1067  2020-05-21 16:36:40.915488  ekaterina
1068  2020-05-21 17:49:36.429237      maxim
1069  2020-05-21 18:45:20.441142  valentina
1070  2020-05-21 23:03:06.457819      maxim
1071  2020-05-21 23:23:49.995349      pavel

- Установка datetime в качестве индексного столбца

In [16]:
df.set_index("datetime", inplace=True)

df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## 2. Переименовывание datetimeв в date_time

In [17]:
df.index.name = "date_time"

df

                                 user
date_time
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## 3. to_csv

In [18]:
df.to_csv(
    output_file, 
    sep=";"
    )